# Generated by Django 3.0.2 on 2020-02-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200207_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
