# Generated by Django 3.0.2 on 2020-02-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200209_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Ключевое слово')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AddField(
            model_name='message',
            name='kwords',
            field=models.ManyToManyField(to='main.Keyword', verbose_name='Ключевые слова'),
        ),
    ]
