# Generated by Django 3.0.2 on 2020-02-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('director', models.CharField(max_length=100, verbose_name='ФИО руководителя (контактного лица)')),
                ('summary', models.TextField(max_length=1000, verbose_name='Краткое описание')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, height_field=300, upload_to='', verbose_name='Фото', width_field=200)),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('summary', models.TextField(max_length=1000, verbose_name='Описание')),
                ('project_start', models.DateField(verbose_name='Сроки начала')),
                ('project_end', models.DateField(verbose_name='Срок окончания')),
                ('project_cost', models.IntegerField(verbose_name='Стоимость')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, choices=[('z', 'Заявка'), ('p', 'Письмо'), ('s', 'Сайт'), ('v', 'Входящее письмо'), ('i', 'Инициатива компании')], default='z', max_length=1, verbose_name='Канал обращения')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('mark', models.CharField(choices=[('l', 'Like'), ('d', 'Dislike')], max_length=1, verbose_name='Оценка')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.Manager', verbose_name='Менеджер')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.Project')),
            ],
        ),
    ]
