# Generated by Django 3.0.2 on 2020-02-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='photo',
        ),
    ]
