# Generated by Django 3.0.2 on 2020-02-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_auto_20200207_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='surname',
        ),
    ]
