# Generated by Django 3.0.2 on 2020-02-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_manager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Фото'),
        ),
    ]
