# Generated by Django 3.0.3 on 2020-02-16 15:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_auto_20200210_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='summary',
            field=ckeditor.fields.RichTextField(verbose_name='Краткое описание'),
        ),
    ]
